-- Run the FULL script in Supabase → SQL Editor.
-- Deleting an account from inside the app: the account is disabled at once, and
-- the actual removal is left to an admin here.
--
-- Nothing in this file gives the app new reach. A signed-in user cannot write
-- profiles.disabled_at (the entitlements trigger strips it) and cannot touch
-- auth.users at all. One function, acting only on auth.uid() and only in one
-- direction, is what turns their own account off; the deletion itself stays with
-- an admin, who already has admin_delete_user.
--
-- Run after schema.sql, premium_sync.sql, admin_list_users.sql, profiles_guard.sql.

-- count_admin_profiles belongs to admin_list_users.sql, which a project may be
-- running from before that function was added to it. Since the body below only
-- calls it at run time, Postgres accepts this file happily and the first person
-- to ask for deletion is the one who finds out. Supplied here when missing, and
-- never replaced: admin_list_users.sql owns the real one, and re-running this
-- file must not put an older allowlist back.
do $$
begin
  if not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'count_admin_profiles'
  ) then
    execute $fn$
      create function public.count_admin_profiles()
      returns integer
      language sql
      security definer
      stable
      set search_path = public
      as $body$
        select count(*)::int
        from public.profiles p
        where p.role = 'admin'
           or lower(coalesce(p.email, '')) in (
             'g.ramkumar3127@gmail.com',
             'lakshmankumar586@gmail.com'
           );
      $body$;
    $fn$;
    execute 'revoke all on function public.count_admin_profiles() from public';
    execute 'grant execute on function public.count_admin_profiles() to authenticated';
  end if;
end $$;

alter table public.profiles
  add column if not exists disabled_at timestamptz;

alter table public.profiles
  add column if not exists disabled_reason text;

comment on column public.profiles.disabled_at is
  'Set when the user asked for deletion. The app refuses to stay signed in while this is set.';

-- Operational queue: who is waiting to be deleted. Keyed on the account, so a
-- finished deletion takes its request with it and the queue cannot grow stale.
create table if not exists public.account_deletion_requests (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  reason_code text not null,
  note text,
  was_premium boolean not null default false,
  requested_at timestamptz not null default now()
);

alter table public.account_deletion_requests enable row level security;

drop policy if exists "Admins read deletion requests" on public.account_deletion_requests;
create policy "Admins read deletion requests"
  on public.account_deletion_requests for select
  using (public.is_profile_admin());

-- Why people leave, kept as a statistic rather than a record of a person: no
-- user id, so it survives the deletion it describes without naming anyone.
create table if not exists public.account_deletion_reasons (
  id bigint generated by default as identity primary key,
  reason_code text not null,
  note text,
  was_premium boolean not null default false,
  account_age_days integer,
  created_at timestamptz not null default now()
);

alter table public.account_deletion_reasons enable row level security;

drop policy if exists "Admins read deletion reasons" on public.account_deletion_reasons;
create policy "Admins read deletion reasons"
  on public.account_deletion_reasons for select
  using (public.is_profile_admin());

revoke all on table public.account_deletion_requests from anon, authenticated;
revoke all on table public.account_deletion_reasons from anon, authenticated;
grant select on table public.account_deletion_requests to authenticated;
grant select on table public.account_deletion_reasons to authenticated;

-- The user's own request. Disables their account and queues it for an admin.
create or replace function public.request_account_deletion(
  reason_code text default null,
  note text default null
)
returns json
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  me uuid := auth.uid();
  code text := coalesce(nullif(btrim(reason_code), ''), 'unsaid');
  clean_note text := nullif(left(btrim(coalesce(note, '')), 1000), '');
  prof record;
begin
  if me is null then
    raise exception 'not authenticated';
  end if;

  -- An admin turning their own account off could leave the app with nobody able
  -- to administer it, including nobody able to action this very request.
  if public.is_profile_admin() and public.count_admin_profiles() <= 1 then
    raise exception 'cannot disable the last admin account';
  end if;

  select p.email, p.full_name, coalesce(p.is_premium, false) as is_premium, p.created_at
  into prof
  from public.profiles p
  where p.id = me;

  update public.profiles
  set disabled_at = coalesce(disabled_at, now()),
      disabled_reason = code,
      active_session_id = null,
      updated_at = now()
  where id = me;

  insert into public.account_deletion_requests (
    user_id, email, full_name, reason_code, note, was_premium
  )
  values (
    me, prof.email, prof.full_name, code, clean_note, coalesce(prof.is_premium, false)
  )
  on conflict (user_id) do update
  set reason_code = excluded.reason_code,
      note = excluded.note,
      requested_at = now();

  insert into public.account_deletion_reasons (
    reason_code, note, was_premium, account_age_days
  )
  values (
    code,
    clean_note,
    coalesce(prof.is_premium, false),
    greatest(0, extract(day from now() - coalesce(prof.created_at, now()))::int)
  );

  return json_build_object('ok', true, 'disabled', true);
end;
$$;

revoke all on function public.request_account_deletion(text, text) from public;
grant execute on function public.request_account_deletion(text, text) to authenticated;

-- Whether this account may still be used: one fact, asked two ways, so the app
-- and the policies below can never disagree about it.
create or replace function public.account_is_active()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select not exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.disabled_at is not null
  );
$$;

revoke all on function public.account_is_active() from public;
grant execute on function public.account_is_active() to authenticated;

-- What the app asks on a timer, and on the way in.
create or replace function public.my_account_disabled()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select not public.account_is_active();
$$;

revoke all on function public.my_account_disabled() from public;
grant execute on function public.my_account_disabled() to authenticated;

-- Admin: the queue to work through, newest request first.
create or replace function public.admin_list_deletion_requests()
returns table (
  user_id uuid,
  email text,
  full_name text,
  reason_code text,
  note text,
  was_premium boolean,
  requested_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_profile_admin() then
    raise exception 'not authorized';
  end if;
  return query
  select r.user_id, r.email, r.full_name, r.reason_code, r.note, r.was_premium, r.requested_at
  from public.account_deletion_requests r
  order by r.requested_at desc;
end;
$$;

revoke all on function public.admin_list_deletion_requests() from public;
grant execute on function public.admin_list_deletion_requests() to authenticated;

-- Bill images live in storage, which no foreign key reaches: deleting the auth
-- user takes their rows and leaves their photographs behind. An admin needs to
-- be able to clear another user's folder for a deletion to actually be one.
drop policy if exists "Admins read all bill images" on storage.objects;
create policy "Admins read all bill images"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'bill-images' and public.is_profile_admin());

drop policy if exists "Admins delete all bill images" on storage.objects;
create policy "Admins delete all bill images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'bill-images' and public.is_profile_admin());

-- Admin: put an account back, for the request that turns out to be a mistake.
create or replace function public.admin_restore_account(target_id uuid)
returns json
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_profile_admin() then
    raise exception 'not authorized';
  end if;
  if target_id is null then
    raise exception 'missing user id';
  end if;

  update public.profiles
  set disabled_at = null,
      disabled_reason = null,
      updated_at = now()
  where id = target_id;

  delete from public.account_deletion_requests where user_id = target_id;

  return json_build_object('ok', true, 'id', target_id);
end;
$$;

revoke all on function public.admin_restore_account(uuid) from public;
grant execute on function public.admin_restore_account(uuid) to authenticated;

-- A disabled account stops syncing. The app signs itself out as soon as it
-- notices the flag, and these policies mean a build that somehow does not
-- notice still cannot read or write cloud rows.
--
-- These three policies also live in user_data.sql and user_categories.sql
-- without the active check. Running either of those files again drops the check,
-- so re-run this file after them.
drop policy if exists "Users manage own finance" on public.user_finance;
create policy "Users manage own finance"
  on public.user_finance for all
  using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

drop policy if exists "Users manage own reminders" on public.user_reminders;
create policy "Users manage own reminders"
  on public.user_reminders for all
  using (auth.uid() = user_id and public.account_is_active())
  with check (auth.uid() = user_id and public.account_is_active());

do $$
begin
  if exists (select 1 from pg_tables where schemaname = 'public' and tablename = 'user_categories') then
    execute 'drop policy if exists "Users manage own categories" on public.user_categories';
    execute 'create policy "Users manage own categories" on public.user_categories for all
             using (auth.uid() = user_id and public.account_is_active())
             with check (auth.uid() = user_id and public.account_is_active())';
  end if;
end $$;

-- The entitlements trigger must own the new columns too, or a signed-in user
-- could clear their own disabled_at straight through the REST API. Same shape as
-- profiles_guard.sql — refuse the write rather than quietly undo it — with the
-- two new columns added to the list.
create or replace function public.profiles_guard_entitlements()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_user not in ('anon', 'authenticated') then
    return new;
  end if;
  -- is_profile_admin is granted to authenticated only, so ask it there.
  if current_user = 'authenticated' and public.is_profile_admin() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.role := 'user';
    new.is_premium := false;
    new.premium_since := null;
    new.premium_ended_at := null;
    new.cloud_purge_at := null;
    new.premium_until := null;
    new.premium_billing := null;
    new.premium_pass_until := null;
    new.diamonds := 0;
    new.disabled_at := null;
    new.disabled_reason := null;
    return new;
  end if;

  if new.role is distinct from old.role
    or new.is_premium is distinct from old.is_premium
    or new.premium_since is distinct from old.premium_since
    or new.premium_ended_at is distinct from old.premium_ended_at
    or new.cloud_purge_at is distinct from old.cloud_purge_at
    or new.premium_until is distinct from old.premium_until
    or new.premium_billing is distinct from old.premium_billing
    or new.premium_pass_until is distinct from old.premium_pass_until
    or new.diamonds is distinct from old.diamonds
    or new.disabled_at is distinct from old.disabled_at
    or new.disabled_reason is distinct from old.disabled_reason
  then
    raise exception 'Role, Premium, diamonds and account status are server-managed'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

comment on function public.profiles_guard_entitlements() is
  'Blocks client writes to role / Premium / diamond / disabled columns on profiles.';
