-- Run the FULL script in Supabase → SQL Editor.
-- Reporting an issue or asking for a feature from inside the app: the message is
-- stored here and read by an admin in the app's own Admin screen. No mail app
-- opens, and nothing is sent from the user's own address.
--
-- Nothing in this file gives the app new reach. The table's grants are revoked
-- from anon and authenticated, only an admin may read it, and the single door in
-- is a function that decides every field except the two the user typed: the
-- account, the timestamp and the status are all filled in server-side, so a user
-- cannot post as someone else, cannot mark their own report resolved, and cannot
-- read a word of anybody else's.
--
-- Run after schema.sql, admin_list_users.sql, profiles_guard.sql.

create table if not exists public.feedback_messages (
  id bigint generated by default as identity primary key,
  -- Kept if the account goes: the report is still worth reading afterwards.
  user_id uuid references auth.users (id) on delete set null,
  email text,
  full_name text,
  topic text not null,
  message text not null,
  app_version text,
  platform text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

comment on table public.feedback_messages is
  'Issues and feature requests submitted from the app. Written only by submit_feedback().';

create index if not exists feedback_messages_unread_idx
  on public.feedback_messages (status, created_at desc);

alter table public.feedback_messages enable row level security;

drop policy if exists "Admins read feedback" on public.feedback_messages;
create policy "Admins read feedback"
  on public.feedback_messages for select
  using (public.is_profile_admin());

revoke all on table public.feedback_messages from anon, authenticated;
grant select on table public.feedback_messages to authenticated;

-- The user's own message. Everything but the topic and the words is decided here.
create or replace function public.submit_feedback(
  p_topic text default null,
  p_message text default null,
  p_app_version text default null,
  p_platform text default null
)
returns json
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  me uuid := auth.uid();
  topic text := lower(coalesce(nullif(btrim(p_topic), ''), 'other'));
  body text := btrim(coalesce(p_message, ''));
  sent_today integer;
  recent bigint;
  prof record;
  new_id bigint;
begin
  if me is null then
    raise exception 'not authenticated';
  end if;

  if topic not in ('bug', 'idea', 'other') then
    topic := 'other';
  end if;

  -- Long enough to mean something, short enough that the table cannot be filled
  -- with one submission.
  if length(body) < 5 then
    raise exception 'message too short';
  end if;
  body := left(body, 4000);

  -- A cap rather than a gate: the only thing a signed-in user can do here is
  -- append, so the harm to bound is volume.
  select count(*) into sent_today
  from public.feedback_messages f
  where f.user_id = me and f.created_at > now() - interval '24 hours';

  if sent_today >= 10 then
    raise exception 'too many messages today';
  end if;

  -- A double tap, or a retry after a dropped reply, is the same message twice.
  select f.id into recent
  from public.feedback_messages f
  where f.user_id = me
    and f.message = body
    and f.created_at > now() - interval '10 minutes'
  limit 1;

  if recent is not null then
    return json_build_object('ok', true, 'id', recent, 'duplicate', true);
  end if;

  select p.email, p.full_name into prof
  from public.profiles p
  where p.id = me;

  insert into public.feedback_messages (
    user_id, email, full_name, topic, message, app_version, platform
  )
  values (
    me,
    prof.email,
    prof.full_name,
    topic,
    body,
    nullif(left(btrim(coalesce(p_app_version, '')), 40), ''),
    nullif(left(btrim(coalesce(p_platform, '')), 40), '')
  )
  returning id into new_id;

  return json_build_object('ok', true, 'id', new_id);
end;
$$;

revoke all on function public.submit_feedback(text, text, text, text) from public;
grant execute on function public.submit_feedback(text, text, text, text) to authenticated;

-- Admin: the inbox, newest first.
create or replace function public.admin_list_feedback(p_limit integer default 200)
returns table (
  id bigint,
  user_id uuid,
  email text,
  full_name text,
  topic text,
  message text,
  app_version text,
  platform text,
  status text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_profile_admin() then
    raise exception 'not authorized';
  end if;
  return query
  select f.id, f.user_id, f.email, f.full_name, f.topic, f.message,
         f.app_version, f.platform, f.status, f.created_at
  from public.feedback_messages f
  order by f.created_at desc
  limit greatest(1, least(coalesce(p_limit, 200), 500));
end;
$$;

revoke all on function public.admin_list_feedback(integer) from public;
grant execute on function public.admin_list_feedback(integer) to authenticated;

-- Admin: read and dealt with, or back to new.
create or replace function public.admin_set_feedback_status(p_id bigint, p_status text)
returns json
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  next_status text := lower(coalesce(nullif(btrim(p_status), ''), 'new'));
begin
  if not public.is_profile_admin() then
    raise exception 'not authorized';
  end if;
  if next_status not in ('new', 'done') then
    raise exception 'unknown status';
  end if;
  update public.feedback_messages
  set status = next_status
  where id = p_id;
  return json_build_object('ok', true, 'status', next_status);
end;
$$;

revoke all on function public.admin_set_feedback_status(bigint, text) from public;
grant execute on function public.admin_set_feedback_status(bigint, text) to authenticated;

-- Admin: throw one away, for the ones that are only noise.
create or replace function public.admin_delete_feedback(p_id bigint)
returns json
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_profile_admin() then
    raise exception 'not authorized';
  end if;
  delete from public.feedback_messages where id = p_id;
  return json_build_object('ok', true);
end;
$$;

revoke all on function public.admin_delete_feedback(bigint) from public;
grant execute on function public.admin_delete_feedback(bigint) to authenticated;
