import type { ImportSourceRule } from '../../types';

/**
 * Built-in SMS / paste parsers for Indian bank / UPI / card + common delivery apps.
 * Admin can override any rule by id via AppConfig.importRules.rules.
 *
 * Debit vs credit: never match credit on bare "upi" (that flipped sent/debit SMS to income).
 * Covers: debit/credit/sent/withdraw/deposit/deduct, Dr/Cr, IMPS/NEFT/RTGS,
 * purchase/txn, ATM cash, wallet apps, reversals.
 */
const NON_TXN_EXCLUDES = [
  'otp',
  'one time password',
  'verification',
  // Bill / EMI / card due reminders (not a completed txn).
  'is due',
  'are due',
  'min due',
  'minimum due',
  'min.due',
  'min. due',
  'total due',
  'total amount due',
  'card statement',
  'credit card statement',
  'statement is generated',
  'statement generated',
  'bill generated',
  'payment due',
  'emi due',
  'emi reminder',
  'overdue',
  'ignore if paid',
  'ignore if already paid',
  // Future / scheduled — not completed yet (AutoPay reminders).
  'autopay reminder',
  'auto pay reminder',
  'auto-pay reminder',
  'will be deducted',
  'will be debited',
  'will be paid',
  'scheduled to be deducted',
  'scheduled for deduction',
  'scheduled for debit',
  'scheduled for a debit',
  'installment scheduled',
  // Pending refunds (money not moved yet).
  'will be credited',
  'will be refunded',
  'refund initiated',
  'refund will be',
  'refund is being processed',
  // Pre-disbursement / consent alerts (limit available, not spent yet).
  'require consent',
  'requires consent',
  'consent to continue',
  'continue disbursement',
  'are available and require',
  // Failed / declined (no money moved) — completed reversals handled separately.
  'txn failed',
  'transaction failed',
  'failed transaction',
  'txn declined',
  'transaction declined',
  'declined',
  'unsuccessful',
  'insufficient balance',
  'insufficient funds',
  'not successful',
  // Marketing / offers (not a completed txn).
  'pre-approved',
  'pre approved',
  'loan offer',
  'personal loan offer',
  'instant personal loan',
  'apply now',
  'limited period offer',
  'get rewards',
  'congratulations! you are eligible',
  'ready to be used',
  'at your convenience',
  'be used at your convenience',
  'used at your convenience',
  'avail instantly',
  'avail instant',
  'avail now',
  'available instantly',
  'click to avail',
];

export const BUILTIN_IMPORT_RULES: ImportSourceRule[] = [
  {
    id: 'upi-debit',
    name: 'Debit / sent / withdraw',
    enabled: true,
    senders: [],
    bodyIncludes: [
      'debited',
      'debit',
      'deducted',
      'deduct',
      'spent',
      'paid',
      'paying',
      'sent',
      'transferred',
      'transfer',
      'withdrawn',
      'withdrawal',
      'withdraw',
      'purchase',
      'txn of',
      'transaction of',
      'used at',
      'cash withdrawn',
      'atm withdrawal',
      'atm wdl',
      'to vpa',
      'paid to',
      'sent to',
      'upi/dr',
      'upi-dr',
      '/dr/',
      ' dr ',
      'dr:',
      'dr rs',
      'dr. rs',
      'dr inr',
    ],
    bodyExcludes: [...NON_TXN_EXCLUDES, 'credited', 'deposited', 'reversed', 'reversal', 'chargeback'],
    kind: 'expense',
    category: 'Others',
    notePrefix: 'Bank',
    paymentType: 'bank',
    priority: 25,
  },
  {
    id: 'rail-debit',
    name: 'IMPS / NEFT / RTGS out',
    enabled: true,
    senders: [],
    bodyIncludes: ['imps', 'neft', 'rtgs'],
    bodyExcludes: [
      ...NON_TXN_EXCLUDES,
      'credited',
      'received',
      'received in',
      'has been credited',
      'reversed',
      'reversal',
    ],
    kind: 'expense',
    category: 'Others',
    notePrefix: 'Bank transfer',
    paymentType: 'bank',
    priority: 22,
  },
  {
    id: 'upi-credit',
    name: 'Credit / deposit / received',
    enabled: true,
    senders: [],
    bodyIncludes: [
      'credited',
      'credit',
      'received',
      'deposited',
      'deposit',
      'from vpa',
      'cash deposited',
      'cash deposit',
      ' cr ',
      'cr:',
      'cr rs',
      'cr. rs',
      'cr inr',
      'upi/cr',
      'upi-cr',
      '/cr/',
    ],
    bodyExcludes: [
      ...NON_TXN_EXCLUDES,
      'debited',
      'debit',
      'deducted',
      'deduct',
      'spent',
      'paid',
      'paying',
      'sent',
      'transferred',
      'transfer',
      'withdraw',
      'withdrawn',
      'withdrawal',
      'to vpa',
      'purchase',
      'used at',
    ],
    kind: 'income',
    category: 'Others',
    notePrefix: 'Bank',
    paymentType: 'bank',
    priority: 20,
  },
  {
    id: 'rail-credit',
    name: 'IMPS / NEFT / RTGS in',
    enabled: true,
    senders: [],
    bodyIncludes: [
      'imps received',
      'neft received',
      'rtgs received',
      'received via imps',
      'received through imps',
      'received by imps',
      'credited via imps',
      'credited by imps',
      'credited through imps',
      'imps credit',
      'neft credit',
      'rtgs credit',
      'imps credited',
      'neft credited',
      'rtgs credited',
    ],
    bodyExcludes: [
      ...NON_TXN_EXCLUDES,
      'debited',
      'deducted',
      'sent to',
      'from your',
      'reversed',
      'reversal',
    ],
    kind: 'income',
    category: 'Others',
    notePrefix: 'Bank transfer',
    paymentType: 'bank',
    priority: 21,
  },
  {
    id: 'txn-reversal',
    name: 'Reversal / chargeback',
    enabled: true,
    senders: [],
    bodyIncludes: ['reversed', 'reversal', 'chargeback', 'txn reversed', 'transaction reversed'],
    bodyExcludes: ['otp', 'one time password', 'verification', 'will be'],
    kind: 'income',
    category: 'Others',
    notePrefix: 'Reversal',
    paymentType: 'bank',
    priority: 35,
  },
  {
    id: 'phonepe',
    name: 'PhonePe',
    enabled: true,
    senders: ['PHONEPE', 'AD-PHONPE', 'VM-PHONPE', 'AX-PHONPE'],
    bodyIncludes: ['phonepe', 'paid', 'sent', 'received', '₹', 'rs', 'debited', 'credited'],
    bodyExcludes: ['otp', 'verification', 'will be'],
    kind: 'expense',
    category: 'Others',
    notePrefix: 'PhonePe',
    paymentType: 'upi',
    priority: 38,
  },
  {
    id: 'paytm',
    name: 'Paytm',
    enabled: true,
    senders: ['PAYTM', 'AD-PAYTM', 'VM-PAYTM', 'AX-PAYTM'],
    bodyIncludes: ['paytm', 'paid', 'sent', 'received', '₹', 'rs', 'debited', 'credited'],
    bodyExcludes: ['otp', 'verification', 'will be'],
    kind: 'expense',
    category: 'Others',
    notePrefix: 'Paytm',
    paymentType: 'upi',
    priority: 38,
  },
  {
    id: 'gpay',
    name: 'Google Pay',
    enabled: true,
    senders: ['GPAY', 'GOOG', 'AD-GOOGPL', 'VM-GOOGPL', 'AX-GOOGLE'],
    bodyIncludes: ['google pay', 'gpay', 'paid', 'sent', 'received', '₹', 'rs', 'debited', 'credited'],
    bodyExcludes: ['otp', 'verification', 'will be'],
    kind: 'expense',
    category: 'Others',
    notePrefix: 'GPay',
    paymentType: 'upi',
    priority: 38,
  },
  {
    id: 'zepto',
    name: 'Zepto',
    enabled: true,
    senders: ['ZEPTO', 'AD-ZEPTO', 'VM-ZEPTO'],
    bodyIncludes: ['zepto', 'order', 'paid', 'delivered', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Groceries',
    notePrefix: 'Zepto',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'blinkit',
    name: 'Blinkit',
    enabled: true,
    senders: ['BLINKIT', 'AD-BLNKIT', 'VM-BLNKIT', 'GROFERS'],
    bodyIncludes: ['blinkit', 'grofers', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Groceries',
    notePrefix: 'Blinkit',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'swiggy',
    name: 'Swiggy',
    enabled: true,
    senders: ['SWIGGY', 'AD-SWIGGY', 'VM-SWIGGY'],
    bodyIncludes: ['swiggy', 'order', 'paid', '₹', 'rs'],
    // Instamart is groceries, not a restaurant order — let the merchant guess route it.
    bodyExcludes: ['otp', 'verification', 'delivery partner', 'instamart'],
    kind: 'expense',
    category: 'Food',
    notePrefix: 'Swiggy',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'zomato',
    name: 'Zomato',
    enabled: true,
    senders: ['ZOMATO', 'AD-ZOMATO', 'VM-ZOMATO'],
    bodyIncludes: ['zomato', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Food',
    notePrefix: 'Zomato',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'amazon',
    name: 'Amazon',
    enabled: true,
    senders: ['AMAZON', 'AD-AMAZON', 'VM-AMAZON'],
    bodyIncludes: ['amazon', 'order', 'paid', '₹', 'rs', 'inr'],
    bodyExcludes: ['otp', 'verification', 'prime video'],
    kind: 'expense',
    category: 'Shopping',
    notePrefix: 'Amazon',
    paymentType: 'card',
    priority: 30,
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    enabled: true,
    senders: ['FLPKRT', 'FLIPKART', 'AD-FLPKRT'],
    bodyIncludes: ['flipkart', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Shopping',
    notePrefix: 'Flipkart',
    paymentType: 'upi',
    priority: 30,
  },
];
