import type { ImportSourceRule } from '../../types';

/**
 * Built-in SMS / paste parsers for Indian bank / UPI / card + common delivery apps.
 * Admin can override any rule by id via AppConfig.importRules.rules.
 *
 * Debit vs credit: never match credit on bare "upi" (that flipped sent/debit SMS to income).
 * Txn verbs: debit, credit, sent, withdraw, deposit (+ common bank variants).
 */
export const BUILTIN_IMPORT_RULES: ImportSourceRule[] = [
  {
    id: 'upi-debit',
    name: 'Debit / sent / withdraw',
    enabled: true,
    // Empty senders = any SMS address; body verbs are the gate.
    senders: [],
    bodyIncludes: [
      'debited',
      'debit',
      'spent',
      'paid',
      'paying',
      'sent',
      'transferred',
      'transfer',
      'withdrawn',
      'withdrawal',
      'withdraw',
      'to vpa',
      'paid to',
      'sent to',
      'upi/dr',
      'upi-dr',
      '/dr/',
    ],
    // Do NOT exclude "received" — HDFC debit footers often say "if not received".
    bodyExcludes: ['otp', 'one time password', 'credited', 'deposited', 'verification'],
    kind: 'expense',
    category: 'Others',
    notePrefix: 'Bank',
    paymentType: 'bank',
    priority: 25,
  },
  {
    id: 'upi-credit',
    name: 'Credit / deposit / received',
    enabled: true,
    senders: [],
    // Do NOT include bare "upi" — that matched debit SMS as credit.
    // "credit" is word-matched; "credit card" alone does not count (see parseImportText).
    bodyIncludes: ['credited', 'credit', 'received', 'deposited', 'deposit', 'from vpa'],
    bodyExcludes: [
      'otp',
      'one time password',
      'debited',
      'debit',
      'spent',
      'paid',
      'paying',
      'sent',
      'transferred',
      'transfer',
      'withdraw',
      'withdrawn',
      'withdrawal',
      'to vpa',
      'verification',
    ],
    kind: 'income',
    category: 'Others',
    notePrefix: 'Bank',
    paymentType: 'bank',
    priority: 20,
  },
  {
    id: 'zepto',
    name: 'Zepto',
    enabled: true,
    senders: ['ZEPTO', 'AD-ZEPTO', 'VM-ZEPTO'],
    bodyIncludes: ['zepto', 'order', 'paid', 'delivered', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Groceries',
    notePrefix: 'Zepto',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'blinkit',
    name: 'Blinkit',
    enabled: true,
    senders: ['BLINKIT', 'AD-BLNKIT', 'VM-BLNKIT', 'GROFERS'],
    bodyIncludes: ['blinkit', 'grofers', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Groceries',
    notePrefix: 'Blinkit',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'swiggy',
    name: 'Swiggy',
    enabled: true,
    senders: ['SWIGGY', 'AD-SWIGGY', 'VM-SWIGGY'],
    bodyIncludes: ['swiggy', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification', 'delivery partner'],
    kind: 'expense',
    category: 'Food',
    notePrefix: 'Swiggy',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'zomato',
    name: 'Zomato',
    enabled: true,
    senders: ['ZOMATO', 'AD-ZOMATO', 'VM-ZOMATO'],
    bodyIncludes: ['zomato', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Food',
    notePrefix: 'Zomato',
    paymentType: 'upi',
    priority: 40,
  },
  {
    id: 'amazon',
    name: 'Amazon',
    enabled: true,
    senders: ['AMAZON', 'AD-AMAZON', 'VM-AMAZON'],
    bodyIncludes: ['amazon', 'order', 'paid', '₹', 'rs', 'inr'],
    bodyExcludes: ['otp', 'verification', 'prime video'],
    kind: 'expense',
    category: 'Shopping',
    notePrefix: 'Amazon',
    paymentType: 'card',
    priority: 30,
  },
  {
    id: 'flipkart',
    name: 'Flipkart',
    enabled: true,
    senders: ['FLPKRT', 'FLIPKART', 'AD-FLPKRT'],
    bodyIncludes: ['flipkart', 'order', 'paid', '₹', 'rs'],
    bodyExcludes: ['otp', 'verification'],
    kind: 'expense',
    category: 'Shopping',
    notePrefix: 'Flipkart',
    paymentType: 'upi',
    priority: 30,
  },
];
