export type RootStackParamList = {
  Dashboard: undefined;
  Calendar: undefined;
  TxnList: { kind: 'expense' | 'income' };
  Finance: undefined;
  ReminderHub: undefined;
  ExpenseReminder: { reminderId?: string } | undefined;
  MedicineReminder: undefined;
  GroceryReminder: undefined;
  GeneralReminder: undefined;
  ShoppingList: undefined;
  Admin: undefined;
  Profile: undefined;
  AppSettings: undefined;
  AlarmSettings: undefined;
  MyProfile: undefined;
  CategorySettings: undefined;
  Themes: undefined;
  AvatarSettings: undefined;
  HomePageSettings: undefined;
  MyCashBooks: undefined;
  Accounts: undefined;
  CreditCards: undefined;
  LanguageSettings: undefined;
  LegalDocument: { kind: 'terms' | 'privacy' };
  Help: undefined;
  Faq: undefined;
  About: undefined;
  Feedback: undefined;
  PremiumCompare: undefined;
  Diamonds: undefined;
  AllTransactions: undefined;
  ImportTransactions: { startSmsScan?: boolean } | undefined;
  Notifications: undefined;
  DeleteAccount: undefined;
};
